version: '2'
services:
    oscar3-app:
        image: oscar3
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://oscar3-postgresql:5432/oscar3
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    oscar3-postgresql:
        extends:
            file: postgresql.yml
            service: oscar3-postgresql
